/**
 * 企业基本信息 — 共享数据源
 * 供政府端 ent-manage.html、政府端 task-manage.html 共同引用
 * 单一数据源，确保企业数据一致
 */

'use strict';

var SHARED_ENTERPRISE_DATA = [
      {
            "name": "南头街道商业广场",
            "code": "91440300MA02BC271",
            "domain": "商业综合体",
            "grid": "南山区-南头街道-南头城社区",
            "bizAddr": "南山区南头街道南头城社区",
            "account": "admin125",
            "status": "停用",
            "date": "2026-06-09 11:14",
            "gridId": "440305001_南头城社区",
            "hasUsers": false,
            "leader": "王建国",
            "phone": "15890779946",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区应急管理局",
            "localDept": "南头街道办",
            "domainId": "COMM_002"
      },
      {
            "name": "南山街道雅居物业",
            "code": "91440300MA0297F5F",
            "domain": "物业小区",
            "grid": "南山区-南山街道-南山社区",
            "bizAddr": "南山区南山街道南山社区",
            "account": "ca792",
            "status": "启用",
            "date": "2026-06-18 09:37",
            "gridId": "440305002_南山社区",
            "hasUsers": true,
            "leader": "李海峰",
            "phone": "18134126396",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "南山街道办",
            "domainId": "COMM_003"
      },
      {
            "name": "沙河街道旺角商场",
            "code": "91440300MA016E30A",
            "domain": "\"三小\"场所（小商店—商场、市场、商店等）",
            "grid": "南山区-沙河街道-侨城北社区",
            "bizAddr": "南山区沙河街道侨城北社区",
            "account": "sz195",
            "status": "启用",
            "date": "2026-02-08 16:38",
            "gridId": "440305003_侨城北社区",
            "hasUsers": true,
            "leader": "张伟",
            "phone": "13702632297",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "沙河街道办",
            "domainId": "COMM_006"
      },
      {
            "name": "蛇口街道美食餐饮店",
            "code": "91440300MA0422946",
            "domain": "\"三小\"场所（小餐饮（燃气））",
            "grid": "南山区-蛇口街道-后海社区",
            "bizAddr": "南山区蛇口街道后海社区",
            "account": "ns833",
            "status": "启用",
            "date": "2026-06-23 16:26",
            "gridId": "440305004_后海社区",
            "hasUsers": true,
            "leader": "刘丽华",
            "phone": "15582334538",
            "industryDept": "南山区文化广电旅游体育局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_007"
      },
      {
            "name": "招商街道美发工作室",
            "code": "91440300MA05679C1",
            "domain": "\"三小\"场所（小美容休闲—理发、美容、纹身、采耳、理疗、针灸、足浴、按摩等）",
            "grid": "南山区-招商街道-蛇口社区",
            "bizAddr": "南山区招商街道蛇口社区",
            "account": "sk928",
            "status": "启用",
            "date": "2026-01-25 10:44",
            "gridId": "440305005_蛇口社区",
            "hasUsers": true,
            "leader": "陈志强",
            "phone": "18465341213",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区应急管理局",
            "localDept": "招商街道办",
            "domainId": "COMM_008"
      },
      {
            "name": "粤海街道咖啡简餐",
            "code": "91440300MA05664D3",
            "domain": "\"三小\"场所（小餐饮（仅用电））",
            "grid": "南山区-粤海街道-深圳湾社区",
            "bizAddr": "南山区粤海街道深圳湾社区",
            "account": "qh259",
            "status": "启用",
            "date": "2026-02-25 13:06",
            "gridId": "440305006_深圳湾社区",
            "hasUsers": true,
            "leader": "杨秀英",
            "phone": "13507943839",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "粤海街道办",
            "domainId": "COMM_009"
      },
      {
            "name": "桃源街道网咖",
            "code": "91440300MA02804A7",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-桃源街道-长源社区",
            "bizAddr": "南山区桃源街道长源社区",
            "account": "yh467",
            "status": "启用",
            "date": "2026-03-20 12:51",
            "gridId": "440305007_长源社区",
            "hasUsers": true,
            "leader": "黄明",
            "phone": "13883543540",
            "industryDept": "南山区交通运输局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "桃源街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "西丽街道汽配经营部",
            "code": "91440300MA084DF1E",
            "domain": "\"三小\"场所（小门店—汽配、废品、五金、打印等）",
            "grid": "南山区-西丽街道-长岭社区",
            "bizAddr": "南山区西丽街道长岭社区",
            "account": "xl649",
            "status": "停用",
            "date": "2026-01-13 09:35",
            "gridId": "440305008_长岭社区",
            "hasUsers": false,
            "leader": "赵小红",
            "phone": "17990566476",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "西丽街道办",
            "domainId": "COMM_011"
      },
      {
            "name": "前海合作区托育中心",
            "code": "91440300MA06BD65C",
            "domain": "\"三小\"场所（小型学校幼儿园—托幼、晚托班、午休班、培训机构等）",
            "grid": "南山区-前海合作区-前海合作区社区",
            "bizAddr": "南山区前海合作区前海合作区社区",
            "account": "nt691",
            "status": "启用",
            "date": "2026-02-23 09:02",
            "gridId": "440305009_前海合作区社区",
            "hasUsers": true,
            "leader": "周强",
            "phone": "15930075810",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区应急管理局",
            "localDept": "前海合作区办",
            "domainId": "COMM_012"
      },
      {
            "name": "南头街道多业态综合楼",
            "code": "91440300MA0595794",
            "domain": "\"三小\"场所（小型多业态场所）",
            "grid": "南山区-南头街道-南光社区",
            "bizAddr": "南山区南头街道南光社区",
            "account": "sg181",
            "status": "启用",
            "date": "2026-02-28 09:24",
            "gridId": "440305001_南光社区",
            "hasUsers": true,
            "leader": "吴芳",
            "phone": "17586845604",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "南头街道办",
            "domainId": "COMM_013"
      },
      {
            "name": "南山街道中医馆",
            "code": "91440300MA06CA7E4",
            "domain": "\"三小\"场所（小型医疗机构—口腔、中医等）",
            "grid": "南山区-南山街道-向南瑞峰社区",
            "bizAddr": "南山区南山街道向南瑞峰社区",
            "account": "admin266",
            "status": "启用",
            "date": "2026-03-12 11:42",
            "gridId": "440305002_向南瑞峰社区",
            "hasUsers": true,
            "leader": "王建国",
            "phone": "17853573823",
            "industryDept": "南山区文化广电旅游体育局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "南山街道办",
            "domainId": "COMM_014"
      },
      {
            "name": "沙河街道剧本杀馆",
            "code": "91440300MA02189AF",
            "domain": "\"三小\"场所（小歌舞娱乐—小ktv、酒吧、密室逃脱、剧本杀等）",
            "grid": "南山区-沙河街道-沙河天健社区",
            "bizAddr": "南山区沙河街道沙河天健社区",
            "account": "ca723",
            "status": "启用",
            "date": "2026-06-06 16:46",
            "gridId": "440305003_沙河天健社区",
            "hasUsers": true,
            "leader": "李海峰",
            "phone": "15275452091",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "沙河街道办",
            "domainId": "COMM_015"
      },
      {
            "name": "蛇口街道加工厂",
            "code": "91440300MA08598EF",
            "domain": "\"三小\"场所（小生产加工企业）",
            "grid": "南山区-蛇口街道-龟山二社区",
            "bizAddr": "南山区蛇口街道龟山二社区",
            "account": "sz488",
            "status": "启用",
            "date": "2026-03-21 16:14",
            "gridId": "440305004_龟山二社区",
            "hasUsers": true,
            "leader": "张伟",
            "phone": "17924970419",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区应急管理局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_016"
      },
      {
            "name": "招商街道民宿",
            "code": "91440300MA01D9433",
            "domain": "\"三小\"场所（小旅店—群租房、公寓、民宿等）",
            "grid": "南山区-招商街道-文竹园社区",
            "bizAddr": "南山区招商街道文竹园社区",
            "account": "ns334",
            "status": "启用",
            "date": "2026-01-26 13:25",
            "gridId": "440305005_文竹园社区",
            "hasUsers": true,
            "leader": "刘丽华",
            "phone": "17171069472",
            "industryDept": "南山区交通运输局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "招商街道办",
            "domainId": "COMM_017"
      },
      {
            "name": "粤海街道娱乐中心",
            "code": "91440300MA0454538",
            "domain": "\"三小\"场所（小型游乐场）",
            "grid": "南山区-粤海街道-海月社区",
            "bizAddr": "南山区粤海街道海月社区",
            "account": "sk680",
            "status": "停用",
            "date": "2026-06-11 11:41",
            "gridId": "440305006_海月社区",
            "hasUsers": false,
            "leader": "陈志强",
            "phone": "18524806516",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "粤海街道办",
            "domainId": "COMM_018"
      },
      {
            "name": "桃源街道加油站",
            "code": "91440300MA084B990",
            "domain": "加油站",
            "grid": "南山区-桃源街道-光前社区",
            "bizAddr": "南山区桃源街道光前社区",
            "account": "qh246",
            "status": "启用",
            "date": "2026-03-05 11:47",
            "gridId": "440305007_光前社区",
            "hasUsers": true,
            "leader": "杨秀英",
            "phone": "19678722458",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "桃源街道办",
            "domainId": "CHEM_001"
      },
      {
            "name": "西丽街道医药化工公司",
            "code": "91440300MA0528548",
            "domain": "医药化工",
            "grid": "南山区-西丽街道-沙河社区",
            "bizAddr": "南山区西丽街道沙河社区",
            "account": "yh864",
            "status": "停用",
            "date": "2026-05-14 17:25",
            "gridId": "440305008_沙河社区",
            "hasUsers": false,
            "leader": "黄明",
            "phone": "17335493870",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区应急管理局",
            "localDept": "西丽街道办",
            "domainId": "CHEM_002"
      },
      {
            "name": "南头街道幼儿园",
            "code": "91440300MA032ABF5",
            "domain": "\"三小\"场所（小型学校幼儿园—托幼、晚托班、午休班、培训机构等）",
            "grid": "南山区-南头街道-马家龙社区",
            "bizAddr": "南山区南头街道马家龙社区",
            "account": "xl621",
            "status": "启用",
            "date": "2026-04-03 08:55",
            "gridId": "440305001_马家龙社区",
            "hasUsers": true,
            "leader": "赵小红",
            "phone": "13264112119",
            "industryDept": "南山区文化广电旅游体育局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "南头街道办",
            "domainId": "COMM_012"
      },
      {
            "name": "南头街道购物中心",
            "code": "91440300MA03836D4",
            "domain": "商业综合体",
            "grid": "南山区-南头街道-北头社区",
            "bizAddr": "南山区南头街道北头社区",
            "account": "nt911",
            "status": "启用",
            "date": "2026-06-14 17:04",
            "gridId": "440305001_北头社区",
            "hasUsers": true,
            "leader": "周强",
            "phone": "18509760584",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "南头街道办",
            "domainId": "COMM_002"
      },
      {
            "name": "南头街道娱乐中心",
            "code": "91440300MA087145E",
            "domain": "\"三小\"场所（小型游乐场）",
            "grid": "南山区-南头街道-向南社区",
            "bizAddr": "南山区南头街道向南社区",
            "account": "sg641",
            "status": "启用",
            "date": "2026-03-18 08:43",
            "gridId": "440305001_向南社区",
            "hasUsers": true,
            "leader": "吴芳",
            "phone": "13831980933",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "南头街道办",
            "domainId": "COMM_018"
      },
      {
            "name": "南山街道幼儿园",
            "code": "91440300MA05390E7",
            "domain": "\"三小\"场所（小型学校幼儿园—托幼、晚托班、午休班、培训机构等）",
            "grid": "南山区-南山街道-南光社区",
            "bizAddr": "南山区南山街道南光社区",
            "account": "admin887",
            "status": "启用",
            "date": "2026-06-11 09:18",
            "gridId": "440305002_南光社区",
            "hasUsers": true,
            "leader": "王建国",
            "phone": "18269820594",
            "industryDept": "南山区交通运输局",
            "professionalDept": "南山区应急管理局",
            "localDept": "南山街道办",
            "domainId": "COMM_012"
      },
      {
            "name": "南山街道老街火锅",
            "code": "91440300MA083697C",
            "domain": "\"三小\"场所（小餐饮（燃气））",
            "grid": "南山区-南山街道-南园社区",
            "bizAddr": "南山区南山街道南园社区",
            "account": "ca103",
            "status": "停用",
            "date": "2026-06-24 12:32",
            "gridId": "440305002_南园社区",
            "hasUsers": false,
            "leader": "李海峰",
            "phone": "15645119047",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "南山街道办",
            "domainId": "COMM_007"
      },
      {
            "name": "南山街道网络休闲中心",
            "code": "91440300MA02A7FFD",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-南山街道-北头社区",
            "bizAddr": "南山区南山街道北头社区",
            "account": "sz991",
            "status": "启用",
            "date": "2026-06-10 16:38",
            "gridId": "440305002_北头社区",
            "hasUsers": true,
            "leader": "张伟",
            "phone": "15264109919",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "南山街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "沙河街道网咖",
            "code": "91440300MA06EFB11",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-沙河街道-白石洲社区",
            "bizAddr": "南山区沙河街道白石洲社区",
            "account": "ns880",
            "status": "启用",
            "date": "2026-02-18 16:58",
            "gridId": "440305003_白石洲社区",
            "hasUsers": true,
            "leader": "刘丽华",
            "phone": "13743111853",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "沙河街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "沙河街道购物中心",
            "code": "91440300MA0623E24",
            "domain": "商业综合体",
            "grid": "南山区-沙河街道-沙河社区",
            "bizAddr": "南山区沙河街道沙河社区",
            "account": "sk600",
            "status": "启用",
            "date": "2026-01-04 13:56",
            "gridId": "440305003_沙河社区",
            "hasUsers": true,
            "leader": "陈志强",
            "phone": "17357109965",
            "industryDept": "南山区文化广电旅游体育局",
            "professionalDept": "南山区应急管理局",
            "localDept": "沙河街道办",
            "domainId": "COMM_002"
      },
      {
            "name": "沙河街道侨城剧本杀馆",
            "code": "91440300MA01E166F",
            "domain": "\"三小\"场所（小歌舞娱乐—小ktv、酒吧、密室逃脱、剧本杀等）",
            "grid": "南山区-沙河街道-侨城东社区",
            "bizAddr": "南山区沙河街道侨城东社区",
            "account": "qh346",
            "status": "启用",
            "date": "2026-05-03 09:46",
            "gridId": "440305003_侨城东社区",
            "hasUsers": true,
            "leader": "杨秀英",
            "phone": "18976198296",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "沙河街道办",
            "domainId": "COMM_015"
      },
      {
            "name": "蛇口街道轻食餐厅",
            "code": "91440300MA020FA29",
            "domain": "\"三小\"场所（小餐饮（仅用电））",
            "grid": "南山区-蛇口街道-南水社区",
            "bizAddr": "南山区蛇口街道南水社区",
            "account": "yh878",
            "status": "启用",
            "date": "2026-05-25 10:08",
            "gridId": "440305004_南水社区",
            "hasUsers": true,
            "leader": "黄明",
            "phone": "18690347116",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "蛇口街道办",
            "domainId": "COMM_009"
      },
      {
            "name": "蛇口街道电竞馆",
            "code": "91440300MA0398802",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-蛇口街道-龟山社区",
            "bizAddr": "南山区蛇口街道龟山社区",
            "account": "xl371",
            "status": "启用",
            "date": "2026-05-28 17:27",
            "gridId": "440305004_龟山社区",
            "hasUsers": true,
            "leader": "赵小红",
            "phone": "15679064766",
            "industryDept": "南山区交通运输局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "蛇口街道健康理疗馆",
            "code": "91440300MA042C0E2",
            "domain": "\"三小\"场所（小美容休闲—理发、美容、纹身、采耳、理疗、针灸、足浴、按摩等）",
            "grid": "南山区-蛇口街道-蛇口社区",
            "bizAddr": "南山区蛇口街道蛇口社区",
            "account": "nt830",
            "status": "停用",
            "date": "2026-03-13 13:28",
            "gridId": "440305004_蛇口社区",
            "hasUsers": false,
            "leader": "周强",
            "phone": "19584779555",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区应急管理局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_008"
      },
      {
            "name": "招商街道轻食餐厅",
            "code": "91440300MA02E3C61",
            "domain": "\"三小\"场所（小餐饮（仅用电））",
            "grid": "南山区-招商街道-鲸山社区",
            "bizAddr": "南山区招商街道鲸山社区",
            "account": "sg353",
            "status": "启用",
            "date": "2026-02-03 13:01",
            "gridId": "440305005_鲸山社区",
            "hasUsers": true,
            "leader": "吴芳",
            "phone": "19694768704",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "招商街道办",
            "domainId": "COMM_009"
      },
      {
            "name": "招商街道华联超市",
            "code": "91440300MA04A2B0C",
            "domain": "\"三小\"场所（小商店—商场、市场、商店等）",
            "grid": "南山区-招商街道-水湾社区",
            "bizAddr": "南山区招商街道水湾社区",
            "account": "admin702",
            "status": "启用",
            "date": "2026-02-01 09:45",
            "gridId": "440305005_水湾社区",
            "hasUsers": true,
            "leader": "王建国",
            "phone": "13345824373",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "招商街道办",
            "domainId": "COMM_006"
      },
      {
            "name": "招商街道废品回收站",
            "code": "91440300MA0208365",
            "domain": "\"三小\"场所（小门店—汽配、废品、五金、打印等）",
            "grid": "南山区-招商街道-花园城社区",
            "bizAddr": "南山区招商街道花园城社区",
            "account": "ca132",
            "status": "启用",
            "date": "2026-03-03 16:15",
            "gridId": "440305005_花园城社区",
            "hasUsers": true,
            "leader": "李海峰",
            "phone": "17818309417",
            "industryDept": "南山区文化广电旅游体育局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "招商街道办",
            "domainId": "COMM_011"
      },
      {
            "name": "粤海街道公寓",
            "code": "91440300MA08B865F",
            "domain": "\"三小\"场所（小旅店—群租房、公寓、民宿等）",
            "grid": "南山区-粤海街道-麻岭社区",
            "bizAddr": "南山区粤海街道麻岭社区",
            "account": "sz319",
            "status": "启用",
            "date": "2026-05-05 17:36",
            "gridId": "440305006_麻岭社区",
            "hasUsers": true,
            "leader": "张伟",
            "phone": "18360916298",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区应急管理局",
            "localDept": "粤海街道办",
            "domainId": "COMM_017"
      },
      {
            "name": "粤海街道混合经营场所",
            "code": "91440300MA0885701",
            "domain": "\"三小\"场所（小型多业态场所）",
            "grid": "南山区-粤海街道-大冲社区",
            "bizAddr": "南山区粤海街道大冲社区",
            "account": "ns926",
            "status": "启用",
            "date": "2026-04-07 09:06",
            "gridId": "440305006_大冲社区",
            "hasUsers": true,
            "leader": "刘丽华",
            "phone": "18480424119",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "粤海街道办",
            "domainId": "COMM_013"
      },
      {
            "name": "粤海街道网络休闲中心",
            "code": "91440300MA07BB1E6",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-粤海街道-科技园社区",
            "bizAddr": "南山区粤海街道科技园社区",
            "account": "sk520",
            "status": "启用",
            "date": "2026-04-28 08:43",
            "gridId": "440305006_科技园社区",
            "hasUsers": true,
            "leader": "陈志强",
            "phone": "13165082363",
            "industryDept": "南山区交通运输局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "粤海街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "桃源街道花园小区",
            "code": "91440300MA0765470",
            "domain": "物业小区",
            "grid": "南山区-桃源街道-平山社区",
            "bizAddr": "南山区桃源街道平山社区",
            "account": "qh845",
            "status": "停用",
            "date": "2026-03-26 09:15",
            "gridId": "440305007_平山社区",
            "hasUsers": false,
            "leader": "杨秀英",
            "phone": "15304235259",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "桃源街道办",
            "domainId": "COMM_003"
      },
      {
            "name": "中石化桃源街道站",
            "code": "91440300MA0988C45",
            "domain": "加油站",
            "grid": "南山区-桃源街道-龙珠社区",
            "bizAddr": "南山区桃源街道龙珠社区",
            "account": "yh559",
            "status": "启用",
            "date": "2026-02-14 10:17",
            "gridId": "440305007_龙珠社区",
            "hasUsers": true,
            "leader": "黄明",
            "phone": "18368227631",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区应急管理局",
            "localDept": "桃源街道办",
            "domainId": "CHEM_001"
      },
      {
            "name": "桃源街道青年旅舍",
            "code": "91440300MA0228EAC",
            "domain": "\"三小\"场所（小旅店—群租房、公寓、民宿等）",
            "grid": "南山区-桃源街道-龙辉社区",
            "bizAddr": "南山区桃源街道龙辉社区",
            "account": "xl553",
            "status": "启用",
            "date": "2026-05-04 08:41",
            "gridId": "440305007_龙辉社区",
            "hasUsers": true,
            "leader": "赵小红",
            "phone": "19997677788",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "桃源街道办",
            "domainId": "COMM_017"
      },
      {
            "name": "西丽街道养生会所",
            "code": "91440300MA013096B",
            "domain": "\"三小\"场所（小美容休闲—理发、美容、纹身、采耳、理疗、针灸、足浴、按摩等）",
            "grid": "南山区-西丽街道-西丽社区",
            "bizAddr": "南山区西丽街道西丽社区",
            "account": "nt195",
            "status": "启用",
            "date": "2026-02-06 14:31",
            "gridId": "440305008_西丽社区",
            "hasUsers": true,
            "leader": "周强",
            "phone": "18329509408",
            "industryDept": "南山区文化广电旅游体育局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "西丽街道办",
            "domainId": "COMM_008"
      },
      {
            "name": "西丽街道麻磡汽配经营部",
            "code": "91440300MA075ECD3",
            "domain": "\"三小\"场所（小门店—汽配、废品、五金、打印等）",
            "grid": "南山区-西丽街道-麻磡社区",
            "bizAddr": "南山区西丽街道麻磡社区",
            "account": "sg160",
            "status": "启用",
            "date": "2026-02-13 08:24",
            "gridId": "440305008_麻磡社区",
            "hasUsers": true,
            "leader": "吴芳",
            "phone": "17941889393",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "西丽街道办",
            "domainId": "COMM_011"
      },
      {
            "name": "西丽街道咖啡简餐",
            "code": "91440300MA083BDAD",
            "domain": "\"三小\"场所（小餐饮（仅用电））",
            "grid": "南山区-西丽街道-大磡社区",
            "bizAddr": "南山区西丽街道大磡社区",
            "account": "admin392",
            "status": "启用",
            "date": "2026-04-23 16:42",
            "gridId": "440305008_大磡社区",
            "hasUsers": true,
            "leader": "王建国",
            "phone": "18266211829",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区应急管理局",
            "localDept": "西丽街道办",
            "domainId": "COMM_009"
      },
      {
            "name": "前海合作区商业广场",
            "code": "91440300MA03FDF65",
            "domain": "商业综合体",
            "grid": "南山区-前海合作区-前海合作区社区",
            "bizAddr": "南山区前海合作区前海合作区社区",
            "account": "ca403",
            "status": "启用",
            "date": "2026-02-02 17:47",
            "gridId": "440305009_前海合作区社区",
            "hasUsers": true,
            "leader": "李海峰",
            "phone": "19165452690",
            "industryDept": "南山区交通运输局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "前海合作区办",
            "domainId": "COMM_002"
      },
      {
            "name": "前海合作区电竞馆",
            "code": "91440300MA05F8AA7",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-前海合作区-前海合作区社区",
            "bizAddr": "南山区前海合作区前海合作区社区",
            "account": "sz158",
            "status": "停用",
            "date": "2026-01-19 15:32",
            "gridId": "440305009_前海合作区社区",
            "hasUsers": false,
            "leader": "张伟",
            "phone": "19269042105",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "前海合作区办",
            "domainId": "COMM_010"
      },
      {
            "name": "前海合作区生产工坊",
            "code": "91440300MA01DD1E8",
            "domain": "\"三小\"场所（小生产加工企业）",
            "grid": "南山区-前海合作区-前海合作区社区",
            "bizAddr": "南山区前海合作区前海合作区社区",
            "account": "ns620",
            "status": "启用",
            "date": "2026-01-28 10:04",
            "gridId": "440305009_前海合作区社区",
            "hasUsers": true,
            "leader": "刘丽华",
            "phone": "19172972420",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "前海合作区办",
            "domainId": "COMM_016"
      },
      {
            "name": "田厦商业广场",
            "code": "91440300MA076AD5B",
            "domain": "商业综合体",
            "grid": "南山区-南头街道-田厦社区",
            "bizAddr": "南山区南头街道田厦社区",
            "account": "ent001",
            "status": "停用",
            "date": "2026-04-07 17:11",
            "gridId": "440305001_田厦社区",
            "hasUsers": false,
            "leader": "王伟",
            "phone": "15366751099",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区应急管理局",
            "localDept": "南头街道办",
            "domainId": "COMM_002"
      },
      {
            "name": "同乐雅居",
            "code": "91440300MA0315E8E",
            "domain": "物业小区",
            "grid": "南山区-南头街道-同乐社区",
            "bizAddr": "南山区南头街道同乐社区",
            "account": "ent002",
            "status": "启用",
            "date": "2026-01-09 14:33",
            "gridId": "440305001_同乐社区",
            "hasUsers": true,
            "leader": "李芳",
            "phone": "19196460984",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "南头街道办",
            "domainId": "COMM_003"
      },
      {
            "name": "大汪便利商店",
            "code": "91440300MA08C835F",
            "domain": "\"三小\"场所（小商店—商场、市场、商店等）",
            "grid": "南山区-南头街道-大汪山社区",
            "bizAddr": "南山区南头街道大汪山社区",
            "account": "ent003",
            "status": "启用",
            "date": "2026-02-14 17:37",
            "gridId": "440305001_大汪山社区",
            "hasUsers": true,
            "leader": "张强",
            "phone": "15951062813",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "南头街道办",
            "domainId": "COMM_006"
      },
      {
            "name": "大新餐饮店",
            "code": "91440300MA06EFF63",
            "domain": "\"三小\"场所（小餐饮（燃气））",
            "grid": "南山区-南头街道-大新社区",
            "bizAddr": "南山区南头街道大新社区",
            "account": "ent004",
            "status": "启用",
            "date": "2026-04-28 11:09",
            "gridId": "440305001_大新社区",
            "hasUsers": true,
            "leader": "刘丽",
            "phone": "18809279383",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "南头街道办",
            "domainId": "COMM_007"
      },
      {
            "name": "九街美发店",
            "code": "91440300MA03D1541",
            "domain": "\"三小\"场所（小美容休闲—理发、美容、纹身、采耳、理疗、针灸、足浴、按摩等）",
            "grid": "南山区-南头街道-九街社区",
            "bizAddr": "南山区南头街道九街社区",
            "account": "ent005",
            "status": "启用",
            "date": "2026-05-11 09:45",
            "gridId": "440305001_九街社区",
            "hasUsers": true,
            "leader": "陈明",
            "phone": "19827328574",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区应急管理局",
            "localDept": "南头街道办",
            "domainId": "COMM_008"
      },
      {
            "name": "龙珠轻食店",
            "code": "91440300MA025BC74",
            "domain": "\"三小\"场所（小餐饮（仅用电））",
            "grid": "南山区-南头街道-龙珠社区",
            "bizAddr": "南山区南头街道龙珠社区",
            "account": "ent006",
            "status": "启用",
            "date": "2026-04-11 14:02",
            "gridId": "440305001_龙珠社区",
            "hasUsers": true,
            "leader": "杨军",
            "phone": "17699096333",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "南头街道办",
            "domainId": "COMM_009"
      },
      {
            "name": "桂庙网咖",
            "code": "91440300MA011359E",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-南头街道-桂庙社区",
            "bizAddr": "南山区南头街道桂庙社区",
            "account": "ent007",
            "status": "启用",
            "date": "2026-04-07 13:59",
            "gridId": "440305001_桂庙社区",
            "hasUsers": true,
            "leader": "黄秀英",
            "phone": "19186775979",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "南头街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "向南汽配店",
            "code": "91440300MA0858D90",
            "domain": "\"三小\"场所（小门店—汽配、废品、五金、打印等）",
            "grid": "南山区-南山街道-向南社区",
            "bizAddr": "南山区南山街道向南社区",
            "account": "ent008",
            "status": "启用",
            "date": "2026-05-07 17:29",
            "gridId": "440305002_向南社区",
            "hasUsers": true,
            "leader": "赵建国",
            "phone": "13483889467",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "南山街道办",
            "domainId": "COMM_011"
      },
      {
            "name": "荔湾幼儿园",
            "code": "91440300MA030518D",
            "domain": "\"三小\"场所（小型学校幼儿园—托幼、晚托班、午休班、培训机构等）",
            "grid": "南山区-南山街道-荔湾社区",
            "bizAddr": "南山区南山街道荔湾社区",
            "account": "ent009",
            "status": "启用",
            "date": "2026-02-23 10:47",
            "gridId": "440305002_荔湾社区",
            "hasUsers": true,
            "leader": "周海峰",
            "phone": "18739324688",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区应急管理局",
            "localDept": "南山街道办",
            "domainId": "COMM_012"
      },
      {
            "name": "荔林多业态楼",
            "code": "91440300MA03CBB1C",
            "domain": "\"三小\"场所（小型多业态场所）",
            "grid": "南山区-南山街道-荔林社区",
            "bizAddr": "南山区南山街道荔林社区",
            "account": "ent010",
            "status": "启用",
            "date": "2026-05-22 10:02",
            "gridId": "440305002_荔林社区",
            "hasUsers": true,
            "leader": "吴小红",
            "phone": "13125022318",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "南山街道办",
            "domainId": "COMM_013"
      },
      {
            "name": "月亮诊所",
            "code": "91440300MA03B152D",
            "domain": "\"三小\"场所（小型医疗机构—口腔、中医等）",
            "grid": "南山区-南山街道-月亮湾社区",
            "bizAddr": "南山区南山街道月亮湾社区",
            "account": "ent011",
            "status": "启用",
            "date": "2026-04-22 14:05",
            "gridId": "440305002_月亮湾社区",
            "hasUsers": true,
            "leader": "徐志强",
            "phone": "18778620616",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "南山街道办",
            "domainId": "COMM_014"
      },
      {
            "name": "前海娱乐馆",
            "code": "91440300MA0254795",
            "domain": "\"三小\"场所（小歌舞娱乐—小ktv、酒吧、密室逃脱、剧本杀等）",
            "grid": "南山区-南山街道-前海社区",
            "bizAddr": "南山区南山街道前海社区",
            "account": "ent012",
            "status": "停用",
            "date": "2026-02-10 17:00",
            "gridId": "440305002_前海社区",
            "hasUsers": false,
            "leader": "孙淑珍",
            "phone": "18454010198",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "南山街道办",
            "domainId": "COMM_015"
      },
      {
            "name": "南水加工坊",
            "code": "91440300MA0320718",
            "domain": "\"三小\"场所（小生产加工企业）",
            "grid": "南山区-南山街道-南水社区",
            "bizAddr": "南山区南山街道南水社区",
            "account": "ent013",
            "status": "启用",
            "date": "2026-05-13 11:57",
            "gridId": "440305002_南水社区",
            "hasUsers": true,
            "leader": "马文",
            "phone": "13787660419",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区应急管理局",
            "localDept": "南山街道办",
            "domainId": "COMM_016"
      },
      {
            "name": "大新民宿",
            "code": "91440300MA04562DD",
            "domain": "\"三小\"场所（小旅店—群租房、公寓、民宿等）",
            "grid": "南山区-南山街道-大新社区",
            "bizAddr": "南山区南山街道大新社区",
            "account": "ent014",
            "status": "启用",
            "date": "2026-04-09 16:25",
            "gridId": "440305002_大新社区",
            "hasUsers": true,
            "leader": "朱华",
            "phone": "15479899005",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "南山街道办",
            "domainId": "COMM_017"
      },
      {
            "name": "登良游乐场",
            "code": "91440300MA08926C8",
            "domain": "\"三小\"场所（小型游乐场）",
            "grid": "南山区-南山街道-登良社区",
            "bizAddr": "南山区南山街道登良社区",
            "account": "ent015",
            "status": "启用",
            "date": "2026-01-05 17:49",
            "gridId": "440305002_登良社区",
            "hasUsers": true,
            "leader": "胡国",
            "phone": "15752872139",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "南山街道办",
            "domainId": "COMM_018"
      },
      {
            "name": "中石化龙瑞站",
            "code": "91440300MA077C890",
            "domain": "加油站",
            "grid": "南山区-南山街道-龙瑞社区",
            "bizAddr": "南山区南山街道龙瑞社区",
            "account": "ent016",
            "status": "启用",
            "date": "2026-01-04 09:09",
            "gridId": "440305002_龙瑞社区",
            "hasUsers": true,
            "leader": "郭辉",
            "phone": "17286976105",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "南山街道办",
            "domainId": "CHEM_001"
      },
      {
            "name": "侨城化工经营部",
            "code": "91440300MA03CBC6D",
            "domain": "医药化工",
            "grid": "南山区-沙河街道-侨城西社区",
            "bizAddr": "南山区沙河街道侨城西社区",
            "account": "ent017",
            "status": "停用",
            "date": "2026-04-05 11:56",
            "gridId": "440305003_侨城西社区",
            "hasUsers": false,
            "leader": "何敏",
            "phone": "19442637958",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区应急管理局",
            "localDept": "沙河街道办",
            "domainId": "CHEM_002"
      },
      {
            "name": "侨香购物中心",
            "code": "91440300MA08F0977",
            "domain": "商业综合体",
            "grid": "南山区-沙河街道-侨香社区",
            "bizAddr": "南山区沙河街道侨香社区",
            "account": "ent018",
            "status": "启用",
            "date": "2026-02-28 12:07",
            "gridId": "440305003_侨香社区",
            "hasUsers": true,
            "leader": "林洁",
            "phone": "17299664370",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "沙河街道办",
            "domainId": "COMM_002"
      },
      {
            "name": "光华花园小区",
            "code": "91440300MA021CA5D",
            "domain": "物业小区",
            "grid": "南山区-沙河街道-光华社区",
            "bizAddr": "南山区沙河街道光华社区",
            "account": "ent019",
            "status": "启用",
            "date": "2026-05-10 08:37",
            "gridId": "440305003_光华社区",
            "hasUsers": true,
            "leader": "罗鹏",
            "phone": "13462318017",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "沙河街道办",
            "domainId": "COMM_003"
      },
      {
            "name": "沙河华联超市",
            "code": "91440300MA046A323",
            "domain": "\"三小\"场所（小商店—商场、市场、商店等）",
            "grid": "南山区-沙河街道-沙河西社区",
            "bizAddr": "南山区沙河街道沙河西社区",
            "account": "ent020",
            "status": "启用",
            "date": "2026-04-13 13:52",
            "gridId": "440305003_沙河西社区",
            "hasUsers": true,
            "leader": "高磊",
            "phone": "18514399900",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "沙河街道办",
            "domainId": "COMM_006"
      },
      {
            "name": "新塘美食馆",
            "code": "91440300MA079426D",
            "domain": "\"三小\"场所（小餐饮（燃气））",
            "grid": "南山区-沙河街道-新塘社区",
            "bizAddr": "南山区沙河街道新塘社区",
            "account": "ent021",
            "status": "启用",
            "date": "2026-03-18 09:11",
            "gridId": "440305003_新塘社区",
            "hasUsers": true,
            "leader": "王伟",
            "phone": "13500500978",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区应急管理局",
            "localDept": "沙河街道办",
            "domainId": "COMM_007"
      },
      {
            "name": "燕晗养生馆",
            "code": "91440300MA0754B94",
            "domain": "\"三小\"场所（小美容休闲—理发、美容、纹身、采耳、理疗、针灸、足浴、按摩等）",
            "grid": "南山区-沙河街道-燕晗山社区",
            "bizAddr": "南山区沙河街道燕晗山社区",
            "account": "ent022",
            "status": "启用",
            "date": "2026-04-08 12:54",
            "gridId": "440305003_燕晗山社区",
            "hasUsers": true,
            "leader": "李芳",
            "phone": "15801543876",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "沙河街道办",
            "domainId": "COMM_008"
      },
      {
            "name": "汉京茶饮店",
            "code": "91440300MA05EC96D",
            "domain": "\"三小\"场所（小餐饮（仅用电））",
            "grid": "南山区-沙河街道-汉京九榕台社区",
            "bizAddr": "南山区沙河街道汉京九榕台社区",
            "account": "ent023",
            "status": "停用",
            "date": "2026-01-28 13:13",
            "gridId": "440305003_汉京九榕台社区",
            "hasUsers": false,
            "leader": "张强",
            "phone": "15511838588",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "沙河街道办",
            "domainId": "COMM_009"
      },
      {
            "name": "沙河电竞馆",
            "code": "91440300MA05B2198",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-沙河街道-沙河翰邦社区",
            "bizAddr": "南山区沙河街道沙河翰邦社区",
            "account": "ent024",
            "status": "启用",
            "date": "2026-04-25 09:56",
            "gridId": "440305003_沙河翰邦社区",
            "hasUsers": true,
            "leader": "刘丽",
            "phone": "18552162517",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "沙河街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "光侨五金店",
            "code": "91440300MA050D965",
            "domain": "\"三小\"场所（小门店—汽配、废品、五金、打印等）",
            "grid": "南山区-沙河街道-光侨社区",
            "bizAddr": "南山区沙河街道光侨社区",
            "account": "ent025",
            "status": "启用",
            "date": "2026-01-17 12:58",
            "gridId": "440305003_光侨社区",
            "hasUsers": true,
            "leader": "陈明",
            "phone": "17946327773",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区应急管理局",
            "localDept": "沙河街道办",
            "domainId": "COMM_011"
      },
      {
            "name": "海昌培训中心",
            "code": "91440300MA089655E",
            "domain": "\"三小\"场所（小型学校幼儿园—托幼、晚托班、午休班、培训机构等）",
            "grid": "南山区-蛇口街道-海昌社区",
            "bizAddr": "南山区蛇口街道海昌社区",
            "account": "ent026",
            "status": "启用",
            "date": "2026-05-05 12:27",
            "gridId": "440305004_海昌社区",
            "hasUsers": true,
            "leader": "杨军",
            "phone": "17539517380",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_012"
      },
      {
            "name": "海湾综合楼",
            "code": "91440300MA03811FC",
            "domain": "\"三小\"场所（小型多业态场所）",
            "grid": "南山区-蛇口街道-海湾社区",
            "bizAddr": "南山区蛇口街道海湾社区",
            "account": "ent027",
            "status": "启用",
            "date": "2026-03-13 17:55",
            "gridId": "440305004_海湾社区",
            "hasUsers": true,
            "leader": "黄秀英",
            "phone": "19815951395",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "蛇口街道办",
            "domainId": "COMM_013"
      },
      {
            "name": "工业中医馆",
            "code": "91440300MA07FE998",
            "domain": "\"三小\"场所（小型医疗机构—口腔、中医等）",
            "grid": "南山区-蛇口街道-工业七路社区",
            "bizAddr": "南山区蛇口街道工业七路社区",
            "account": "ent028",
            "status": "启用",
            "date": "2026-02-13 13:56",
            "gridId": "440305004_工业七路社区",
            "hasUsers": true,
            "leader": "赵建国",
            "phone": "15470851735",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_014"
      },
      {
            "name": "花果KTV",
            "code": "91440300MA0105CCB",
            "domain": "\"三小\"场所（小歌舞娱乐—小ktv、酒吧、密室逃脱、剧本杀等）",
            "grid": "南山区-蛇口街道-花果山社区",
            "bizAddr": "南山区蛇口街道花果山社区",
            "account": "ent029",
            "status": "启用",
            "date": "2026-06-12 12:54",
            "gridId": "440305004_花果山社区",
            "hasUsers": true,
            "leader": "周海峰",
            "phone": "15814050576",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区应急管理局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_015"
      },
      {
            "name": "湾厦制造厂",
            "code": "91440300MA03B3415",
            "domain": "\"三小\"场所（小生产加工企业）",
            "grid": "南山区-蛇口街道-湾厦社区",
            "bizAddr": "南山区蛇口街道湾厦社区",
            "account": "ent030",
            "status": "启用",
            "date": "2026-06-09 14:47",
            "gridId": "440305004_湾厦社区",
            "hasUsers": true,
            "leader": "吴小红",
            "phone": "15538350634",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_016"
      },
      {
            "name": "育才公寓",
            "code": "91440300MA067B752",
            "domain": "\"三小\"场所（小旅店—群租房、公寓、民宿等）",
            "grid": "南山区-蛇口街道-育才社区",
            "bizAddr": "南山区蛇口街道育才社区",
            "account": "ent031",
            "status": "启用",
            "date": "2026-06-13 08:07",
            "gridId": "440305004_育才社区",
            "hasUsers": true,
            "leader": "徐志强",
            "phone": "19670960537",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "蛇口街道办",
            "domainId": "COMM_017"
      },
      {
            "name": "渔二乐园",
            "code": "91440300MA0431927",
            "domain": "\"三小\"场所（小型游乐场）",
            "grid": "南山区-蛇口街道-渔二社区",
            "bizAddr": "南山区蛇口街道渔二社区",
            "account": "ent032",
            "status": "启用",
            "date": "2026-01-17 12:43",
            "gridId": "440305004_渔二社区",
            "hasUsers": true,
            "leader": "孙淑珍",
            "phone": "15648806583",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "蛇口街道办",
            "domainId": "COMM_018"
      },
      {
            "name": "龟山加油站",
            "code": "91440300MA080F3E3",
            "domain": "加油站",
            "grid": "南山区-蛇口街道-龟山一社区",
            "bizAddr": "南山区蛇口街道龟山一社区",
            "account": "ent033",
            "status": "启用",
            "date": "2026-02-09 14:29",
            "gridId": "440305004_龟山一社区",
            "hasUsers": true,
            "leader": "马文",
            "phone": "19670190251",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区应急管理局",
            "localDept": "蛇口街道办",
            "domainId": "CHEM_001"
      },
      {
            "name": "南水化工经营部",
            "code": "91440300MA058DC16",
            "domain": "医药化工",
            "grid": "南山区-招商街道-南水社区",
            "bizAddr": "南山区招商街道南水社区",
            "account": "ent034",
            "status": "停用",
            "date": "2026-02-24 08:06",
            "gridId": "440305005_南水社区",
            "hasUsers": false,
            "leader": "朱华",
            "phone": "17181144246",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "招商街道办",
            "domainId": "CHEM_002"
      },
      {
            "name": "南光商业广场",
            "code": "91440300MA01770D6",
            "domain": "商业综合体",
            "grid": "南山区-招商街道-南光社区",
            "bizAddr": "南山区招商街道南光社区",
            "account": "ent035",
            "status": "启用",
            "date": "2026-01-14 12:23",
            "gridId": "440305005_南光社区",
            "hasUsers": true,
            "leader": "胡国",
            "phone": "19772591519",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "招商街道办",
            "domainId": "COMM_002"
      },
      {
            "name": "沿山雅居",
            "code": "91440300MA05AD2AD",
            "domain": "物业小区",
            "grid": "南山区-招商街道-沿山社区",
            "bizAddr": "南山区招商街道沿山社区",
            "account": "ent036",
            "status": "启用",
            "date": "2026-02-25 09:55",
            "gridId": "440305005_沿山社区",
            "hasUsers": true,
            "leader": "郭辉",
            "phone": "18527828713",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "招商街道办",
            "domainId": "COMM_003"
      },
      {
            "name": "望海便利商店",
            "code": "91440300MA03B5B04",
            "domain": "\"三小\"场所（小商店—商场、市场、商店等）",
            "grid": "南山区-招商街道-望海社区",
            "bizAddr": "南山区招商街道望海社区",
            "account": "ent037",
            "status": "启用",
            "date": "2026-03-15 13:08",
            "gridId": "440305005_望海社区",
            "hasUsers": true,
            "leader": "何敏",
            "phone": "15579477785",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区应急管理局",
            "localDept": "招商街道办",
            "domainId": "COMM_006"
      },
      {
            "name": "招商餐饮店",
            "code": "91440300MA072D936",
            "domain": "\"三小\"场所（小餐饮（燃气））",
            "grid": "南山区-招商街道-招商东角头社区",
            "bizAddr": "南山区招商街道招商东角头社区",
            "account": "ent038",
            "status": "启用",
            "date": "2026-04-18 10:23",
            "gridId": "440305005_招商东角头社区",
            "hasUsers": true,
            "leader": "林洁",
            "phone": "17322921164",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "招商街道办",
            "domainId": "COMM_007"
      },
      {
            "name": "蛇口美发店",
            "code": "91440300MA0554B74",
            "domain": "\"三小\"场所（小美容休闲—理发、美容、纹身、采耳、理疗、针灸、足浴、按摩等）",
            "grid": "南山区-招商街道-蛇口工业区社区",
            "bizAddr": "南山区招商街道蛇口工业区社区",
            "account": "ent039",
            "status": "启用",
            "date": "2026-04-19 14:11",
            "gridId": "440305005_蛇口工业区社区",
            "hasUsers": true,
            "leader": "罗鹏",
            "phone": "18715036668",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "招商街道办",
            "domainId": "COMM_008"
      },
      {
            "name": "科技轻食店",
            "code": "91440300MA089348B",
            "domain": "\"三小\"场所（小餐饮（仅用电））",
            "grid": "南山区-粤海街道-科技园东社区",
            "bizAddr": "南山区粤海街道科技园东社区",
            "account": "ent040",
            "status": "启用",
            "date": "2026-06-06 09:34",
            "gridId": "440305006_科技园东社区",
            "hasUsers": true,
            "leader": "高磊",
            "phone": "15593783878",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "粤海街道办",
            "domainId": "COMM_009"
      },
      {
            "name": "高新网咖",
            "code": "91440300MA095310A",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-粤海街道-高新区社区",
            "bizAddr": "南山区粤海街道高新区社区",
            "account": "ent041",
            "status": "启用",
            "date": "2026-01-04 13:50",
            "gridId": "440305006_高新区社区",
            "hasUsers": true,
            "leader": "王伟",
            "phone": "18177464240",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区应急管理局",
            "localDept": "粤海街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "后海汽配店",
            "code": "91440300MA0653605",
            "domain": "\"三小\"场所（小门店—汽配、废品、五金、打印等）",
            "grid": "南山区-粤海街道-后海社区",
            "bizAddr": "南山区粤海街道后海社区",
            "account": "ent042",
            "status": "启用",
            "date": "2026-06-24 08:36",
            "gridId": "440305006_后海社区",
            "hasUsers": true,
            "leader": "李芳",
            "phone": "19395657711",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "粤海街道办",
            "domainId": "COMM_011"
      },
      {
            "name": "后海幼儿园",
            "code": "91440300MA0125514",
            "domain": "\"三小\"场所（小型学校幼儿园—托幼、晚托班、午休班、培训机构等）",
            "grid": "南山区-粤海街道-后海福海社区",
            "bizAddr": "南山区粤海街道后海福海社区",
            "account": "ent043",
            "status": "启用",
            "date": "2026-05-11 14:16",
            "gridId": "440305006_后海福海社区",
            "hasUsers": true,
            "leader": "张强",
            "phone": "15246192537",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "粤海街道办",
            "domainId": "COMM_012"
      },
      {
            "name": "后海多业态楼",
            "code": "91440300MA01B6A73",
            "domain": "\"三小\"场所（小型多业态场所）",
            "grid": "南山区-粤海街道-后海大新社区",
            "bizAddr": "南山区粤海街道后海大新社区",
            "account": "ent044",
            "status": "启用",
            "date": "2026-04-02 08:21",
            "gridId": "440305006_后海大新社区",
            "hasUsers": true,
            "leader": "刘丽",
            "phone": "19346913225",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "粤海街道办",
            "domainId": "COMM_013"
      },
      {
            "name": "滨海诊所",
            "code": "91440300MA05A0CF5",
            "domain": "\"三小\"场所（小型医疗机构—口腔、中医等）",
            "grid": "南山区-粤海街道-滨海之窗社区",
            "bizAddr": "南山区粤海街道滨海之窗社区",
            "account": "ent045",
            "status": "停用",
            "date": "2026-02-27 15:03",
            "gridId": "440305006_滨海之窗社区",
            "hasUsers": false,
            "leader": "陈明",
            "phone": "18346531310",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区应急管理局",
            "localDept": "粤海街道办",
            "domainId": "COMM_014"
      },
      {
            "name": "蔚蓝娱乐馆",
            "code": "91440300MA03F8252",
            "domain": "\"三小\"场所（小歌舞娱乐—小ktv、酒吧、密室逃脱、剧本杀等）",
            "grid": "南山区-粤海街道-蔚蓝海岸社区",
            "bizAddr": "南山区粤海街道蔚蓝海岸社区",
            "account": "ent046",
            "status": "启用",
            "date": "2026-01-16 10:17",
            "gridId": "440305006_蔚蓝海岸社区",
            "hasUsers": true,
            "leader": "杨军",
            "phone": "17805274535",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "粤海街道办",
            "domainId": "COMM_015"
      },
      {
            "name": "海珠加工坊",
            "code": "91440300MA06CBDF2",
            "domain": "\"三小\"场所（小生产加工企业）",
            "grid": "南山区-粤海街道-海珠社区",
            "bizAddr": "南山区粤海街道海珠社区",
            "account": "ent047",
            "status": "启用",
            "date": "2026-01-18 11:49",
            "gridId": "440305006_海珠社区",
            "hasUsers": true,
            "leader": "黄秀英",
            "phone": "19286444583",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "粤海街道办",
            "domainId": "COMM_016"
      },
      {
            "name": "海德民宿",
            "code": "91440300MA069CD2D",
            "domain": "\"三小\"场所（小旅店—群租房、公寓、民宿等）",
            "grid": "南山区-粤海街道-海德社区",
            "bizAddr": "南山区粤海街道海德社区",
            "account": "ent048",
            "status": "启用",
            "date": "2026-06-27 16:05",
            "gridId": "440305006_海德社区",
            "hasUsers": true,
            "leader": "赵建国",
            "phone": "13878192149",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "粤海街道办",
            "domainId": "COMM_017"
      },
      {
            "name": "海风游乐场",
            "code": "91440300MA02F701F",
            "domain": "\"三小\"场所（小型游乐场）",
            "grid": "南山区-粤海街道-海风社区",
            "bizAddr": "南山区粤海街道海风社区",
            "account": "ent049",
            "status": "启用",
            "date": "2026-02-05 16:05",
            "gridId": "440305006_海风社区",
            "hasUsers": true,
            "leader": "周海峰",
            "phone": "13915167217",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区应急管理局",
            "localDept": "粤海街道办",
            "domainId": "COMM_018"
      },
      {
            "name": "中石化华联站",
            "code": "91440300MA09284B9",
            "domain": "加油站",
            "grid": "南山区-粤海街道-华联社区",
            "bizAddr": "南山区粤海街道华联社区",
            "account": "ent050",
            "status": "启用",
            "date": "2026-06-13 10:22",
            "gridId": "440305006_华联社区",
            "hasUsers": true,
            "leader": "吴小红",
            "phone": "15760334051",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "粤海街道办",
            "domainId": "CHEM_001"
      },
      {
            "name": "光华化工经营部",
            "code": "91440300MA03880AC",
            "domain": "医药化工",
            "grid": "南山区-桃源街道-光华社区",
            "bizAddr": "南山区桃源街道光华社区",
            "account": "ent051",
            "status": "停用",
            "date": "2026-03-25 08:57",
            "gridId": "440305007_光华社区",
            "hasUsers": false,
            "leader": "徐志强",
            "phone": "17969116815",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "桃源街道办",
            "domainId": "CHEM_002"
      },
      {
            "name": "茶光购物中心",
            "code": "91440300MA07EE8E6",
            "domain": "商业综合体",
            "grid": "南山区-桃源街道-茶光社区",
            "bizAddr": "南山区桃源街道茶光社区",
            "account": "ent052",
            "status": "启用",
            "date": "2026-02-10 10:47",
            "gridId": "440305007_茶光社区",
            "hasUsers": true,
            "leader": "孙淑珍",
            "phone": "13257373770",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "桃源街道办",
            "domainId": "COMM_002"
      },
      {
            "name": "金桃花园小区",
            "code": "91440300MA08E60A3",
            "domain": "物业小区",
            "grid": "南山区-桃源街道-金桃园社区",
            "bizAddr": "南山区桃源街道金桃园社区",
            "account": "ent053",
            "status": "启用",
            "date": "2026-06-17 08:14",
            "gridId": "440305007_金桃园社区",
            "hasUsers": true,
            "leader": "马文",
            "phone": "18832422838",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区应急管理局",
            "localDept": "桃源街道办",
            "domainId": "COMM_003"
      },
      {
            "name": "金桂华联超市",
            "code": "91440300MA0281509",
            "domain": "\"三小\"场所（小商店—商场、市场、商店等）",
            "grid": "南山区-桃源街道-金桂园社区",
            "bizAddr": "南山区桃源街道金桂园社区",
            "account": "ent054",
            "status": "启用",
            "date": "2026-02-19 15:46",
            "gridId": "440305007_金桂园社区",
            "hasUsers": true,
            "leader": "朱华",
            "phone": "19186091377",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "桃源街道办",
            "domainId": "COMM_006"
      },
      {
            "name": "留仙美食馆",
            "code": "91440300MA03895EF",
            "domain": "\"三小\"场所（小餐饮（燃气））",
            "grid": "南山区-桃源街道-留仙社区",
            "bizAddr": "南山区桃源街道留仙社区",
            "account": "ent055",
            "status": "启用",
            "date": "2026-02-25 15:23",
            "gridId": "440305007_留仙社区",
            "hasUsers": true,
            "leader": "胡国",
            "phone": "17436506774",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "桃源街道办",
            "domainId": "COMM_007"
      },
      {
            "name": "桃源养生馆",
            "code": "91440300MA01AEEBB",
            "domain": "\"三小\"场所（小美容休闲—理发、美容、纹身、采耳、理疗、针灸、足浴、按摩等）",
            "grid": "南山区-桃源街道-桃源村社区",
            "bizAddr": "南山区桃源街道桃源村社区",
            "account": "ent056",
            "status": "停用",
            "date": "2026-05-13 08:19",
            "gridId": "440305007_桃源村社区",
            "hasUsers": false,
            "leader": "郭辉",
            "phone": "15242535202",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "桃源街道办",
            "domainId": "COMM_008"
      },
      {
            "name": "大磡茶饮店",
            "code": "91440300MA012261F",
            "domain": "\"三小\"场所（小餐饮（仅用电））",
            "grid": "南山区-桃源街道-大磡社区",
            "bizAddr": "南山区桃源街道大磡社区",
            "account": "ent057",
            "status": "启用",
            "date": "2026-03-26 16:18",
            "gridId": "440305007_大磡社区",
            "hasUsers": true,
            "leader": "何敏",
            "phone": "17232719732",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区应急管理局",
            "localDept": "桃源街道办",
            "domainId": "COMM_009"
      },
      {
            "name": "白芒电竞馆",
            "code": "91440300MA08D5304",
            "domain": "\"三小\"场所（小网吧）",
            "grid": "南山区-西丽街道-白芒社区",
            "bizAddr": "南山区西丽街道白芒社区",
            "account": "ent058",
            "status": "启用",
            "date": "2026-04-26 09:02",
            "gridId": "440305008_白芒社区",
            "hasUsers": true,
            "leader": "林洁",
            "phone": "17276044853",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "西丽街道办",
            "domainId": "COMM_010"
      },
      {
            "name": "大学五金店",
            "code": "91440300MA0607E85",
            "domain": "\"三小\"场所（小门店—汽配、废品、五金、打印等）",
            "grid": "南山区-西丽街道-大学城社区",
            "bizAddr": "南山区西丽街道大学城社区",
            "account": "ent059",
            "status": "启用",
            "date": "2026-03-22 13:51",
            "gridId": "440305008_大学城社区",
            "hasUsers": true,
            "leader": "罗鹏",
            "phone": "13504430839",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "西丽街道办",
            "domainId": "COMM_011"
      },
      {
            "name": "九祥培训中心",
            "code": "91440300MA0548D28",
            "domain": "\"三小\"场所（小型学校幼儿园—托幼、晚托班、午休班、培训机构等）",
            "grid": "南山区-西丽街道-九祥岭社区",
            "bizAddr": "南山区西丽街道九祥岭社区",
            "account": "ent060",
            "status": "启用",
            "date": "2026-05-08 16:09",
            "gridId": "440305008_九祥岭社区",
            "hasUsers": true,
            "leader": "高磊",
            "phone": "13920017659",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "西丽街道办",
            "domainId": "COMM_012"
      },
      {
            "name": "茶光综合楼",
            "code": "91440300MA0592F5D",
            "domain": "\"三小\"场所（小型多业态场所）",
            "grid": "南山区-西丽街道-茶光社区",
            "bizAddr": "南山区西丽街道茶光社区",
            "account": "ent061",
            "status": "启用",
            "date": "2026-06-13 14:32",
            "gridId": "440305008_茶光社区",
            "hasUsers": true,
            "leader": "王伟",
            "phone": "15286997089",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区应急管理局",
            "localDept": "西丽街道办",
            "domainId": "COMM_013"
      },
      {
            "name": "松坪中医馆",
            "code": "91440300MA0956EF1",
            "domain": "\"三小\"场所（小型医疗机构—口腔、中医等）",
            "grid": "南山区-西丽街道-松坪社区",
            "bizAddr": "南山区西丽街道松坪社区",
            "account": "ent062",
            "status": "启用",
            "date": "2026-04-02 11:15",
            "gridId": "440305008_松坪社区",
            "hasUsers": true,
            "leader": "李芳",
            "phone": "17275916950",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "西丽街道办",
            "domainId": "COMM_014"
      },
      {
            "name": "松坪KTV",
            "code": "91440300MA0274FC8",
            "domain": "\"三小\"场所（小歌舞娱乐—小ktv、酒吧、密室逃脱、剧本杀等）",
            "grid": "南山区-西丽街道-松坪山社区",
            "bizAddr": "南山区西丽街道松坪山社区",
            "account": "ent063",
            "status": "启用",
            "date": "2026-04-01 17:01",
            "gridId": "440305008_松坪山社区",
            "hasUsers": true,
            "leader": "张强",
            "phone": "15241471120",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "西丽街道办",
            "domainId": "COMM_015"
      },
      {
            "name": "西丽制造厂",
            "code": "91440300MA03D4630",
            "domain": "\"三小\"场所（小生产加工企业）",
            "grid": "南山区-西丽街道-西丽湖社区",
            "bizAddr": "南山区西丽街道西丽湖社区",
            "account": "ent064",
            "status": "启用",
            "date": "2026-06-10 08:56",
            "gridId": "440305008_西丽湖社区",
            "hasUsers": true,
            "leader": "刘丽",
            "phone": "17296748293",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "西丽街道办",
            "domainId": "COMM_016"
      },
      {
            "name": "官龙公寓",
            "code": "91440300MA07D7FF1",
            "domain": "\"三小\"场所（小旅店—群租房、公寓、民宿等）",
            "grid": "南山区-西丽街道-官龙村社区",
            "bizAddr": "南山区西丽街道官龙村社区",
            "account": "ent065",
            "status": "启用",
            "date": "2026-02-01 08:32",
            "gridId": "440305008_官龙村社区",
            "hasUsers": true,
            "leader": "陈明",
            "phone": "18579152218",
            "industryDept": "南山区教育局",
            "professionalDept": "南山区应急管理局",
            "localDept": "西丽街道办",
            "domainId": "COMM_017"
      },
      {
            "name": "新围乐园",
            "code": "91440300MA022355F",
            "domain": "\"三小\"场所（小型游乐场）",
            "grid": "南山区-西丽街道-新围社区",
            "bizAddr": "南山区西丽街道新围社区",
            "account": "ent066",
            "status": "启用",
            "date": "2026-02-19 11:21",
            "gridId": "440305008_新围社区",
            "hasUsers": true,
            "leader": "杨军",
            "phone": "18241828677",
            "industryDept": "南山区工业和信息化局",
            "professionalDept": "南山区住房和建设局",
            "localDept": "西丽街道办",
            "domainId": "COMM_018"
      },
      {
            "name": "丽湖加油站",
            "code": "91440300MA089ABB7",
            "domain": "加油站",
            "grid": "南山区-西丽街道-丽湖社区",
            "bizAddr": "南山区西丽街道丽湖社区",
            "account": "ent067",
            "status": "停用",
            "date": "2026-05-03 13:32",
            "gridId": "440305008_丽湖社区",
            "hasUsers": false,
            "leader": "黄秀英",
            "phone": "15349774749",
            "industryDept": "南山区住房和建设局",
            "professionalDept": "南山区消防救援大队",
            "localDept": "西丽街道办",
            "domainId": "CHEM_001"
      },
      {
            "name": "南科化工经营部",
            "code": "91440300MA08B539F",
            "domain": "医药化工",
            "grid": "南山区-西丽街道-南科大社区",
            "bizAddr": "南山区西丽街道南科大社区",
            "account": "ent068",
            "status": "停用",
            "date": "2026-02-23 09:27",
            "gridId": "440305008_南科大社区",
            "hasUsers": false,
            "leader": "赵建国",
            "phone": "19316548063",
            "industryDept": "南山区应急管理局",
            "professionalDept": "南山区生态环境分局",
            "localDept": "西丽街道办",
            "domainId": "CHEM_002"
      },
      {
            "name": "长源商业广场",
            "code": "91440300MA03BB1DF",
            "domain": "商业综合体",
            "grid": "南山区-西丽街道-长源社区",
            "bizAddr": "南山区西丽街道长源社区",
            "account": "ent069",
            "status": "启用",
            "date": "2026-02-16 11:11",
            "gridId": "440305008_长源社区",
            "hasUsers": true,
            "leader": "周海峰",
            "phone": "17280219930",
            "industryDept": "南山区卫生健康局",
            "professionalDept": "南山区应急管理局",
            "localDept": "西丽街道办",
            "domainId": "COMM_002"
      }
    ];
